name: schedule

on:
  schedule:
    - cron: "* * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: run
      run: python discord_test.py
      env:
          AUTHORIZATION_LIST1: ${{ secrets.AUTHORIZATION_LIST1 }}
          CHANEL_LIST1: ${{ secrets.CHANEL_LIST1 }}
