name: schedule

on:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: run
        run: python discord_test.py
        env:
          AUTHORIZATION_LIST1: ${{ secrets.AUTHORIZATION_LIST1 }}
          CHANEL_LIST1: ${{ secrets.CHANEL_LIST1 }}
